---
title: "NC Economic Development"
author: "Christian Okoth"
date: "November 22, 2019"
output: html_document
---

## 1 Overview
Each of you will complete an original research project using data you collect and analyze using gretl (a statistical software package). A very important first step is to choose a topic. Think of one that you find interesting and that you can address with available data. Once I have approved your topic, you cannot change it. Put the time in up front and choose a topic you can live with for the rest of the semester! 
Your topic should be well-defined and enable you to test a specific hypothesis, e.g., a higher literacy rate is a positive and significant determinant of a country’s GDP. Do not choose a topic for which data will be hard to come by, e.g., I want to look at insider trading. 



## 1.1 Requirements
Your data set must contain at least 100 observations and at least 7 variables (1 dependent variable and 6 independent variables. An Excel spreadsheet of this size would have 101 rows  and 8 columns. The first row would contain the variable names and the first column would contain an identifier for each observation, e.g., country name, company name, metropolitan statistical area, etc. Your project data set will be cross-sectional data.

```{r fullset, echo=false}
head(fullset, 20)
```

Your dependent variable must be quantitative and cardinal. Your independent variables may be quantitative or categorical, cardinal or ordinal. All of your independent variables cannot be categorical. Categorical variables must be converted into dummy variables. Finally, you must have at least one dummy variable.

## Project Assignment #3  Due: Thursday, December 5 by 3:00PM Value: 40% of your project grade
All work for this assignment must be done in gretl. This includes all graphs, summary statistics, regressions, and statistical tests.
## Presentation
Your paper must be single-sided, double-spaced with a 12-point font. It must be stapled—no paper clips, dog ears or loose-leaf. Write in complete sentences. 
Use short variable names. This assignment calls for a minimum of 2 regressions. You should copy the full regression output from Gretl and paste it into your paper at the appropriate points. Be sure to use robust errors.